# File name: main1.py

	
<Menu>:
	
	FloatLayout:

        AsyncImage:
            source: 'assets/background/meadow.png'
            pos_hint: {"y": 0.1}

        AsyncImage:
        	source: 'assets/platform/platform1.png'
        	pos_hint: {"top": 0.6}
        	
		AsyncImage:
			source: "assets/start_menu/RunningManLogo.png"
			pos_hint: {"top": 1.05, "right": 0.86}
			size_hint: 0.7, 0.7
	


		
		